---
- name: Testing network ping functionality
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    hostnames:
      - yhost
      - phost
      - ohost
      - whost

  tasks:
  - name: Pinging Outward
    raw: "sudo ip netns exec {{ item }} ip -c link | grep -A 2 {{ item }}"
    register: result
    loop: "{{ hostnames }}"

  - name: Pinging Outward
    raw: "sudo ip netns exec {{ item }} ping -c 2 8.8.8.8"
    register: result
    loop: "{{ hostnames }}"

  - name: Pinging from hosts to core router
    raw: "sudo ip netns exec {{ item }} ping -c 2 10.1.5.17"
    register: result
    loop: "{{ hostnames }}"

  - name: Show results
    debug:
        var: result

  - name: Outputting results to file...
    ansible.builtin.copy:
      content: "{{ result }}"
      dest: networktestsresults.log
